openapi: 3.0.3
info:
  title: FHIR Mapper API's
  description: Conversion of simple json to ABDM compliant FHIR Format bundles
  version: 1.0.0
servers:
  - url: http://localhost:8085/v1/bundle

paths:
  /op-consultation:
    post:
      tags:
        - HI Types
      summary: Create an OP Consultation Record
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OPConsultRecord'
      responses:
        '201':
          description: Successfully created
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/ValidationErrorResponse'
                  - $ref: '#/components/schemas/GenericErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericErrorResponse'
  /prescription:
    post:
      tags:
        - HI Types
      summary: Create a Prescription Record
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PrescriptionRecord'
      responses:
        '201':
          description: Successfully created
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/ValidationErrorResponse'
                  - $ref: '#/components/schemas/GenericErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericErrorResponse'
  /health-document:
    post:
      tags:
        - HI Types
      summary: Create a Health Document Record
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HealthDocumentRecord'
      responses:
        '201':
          description: Successfully created
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/ValidationErrorResponse'
                  - $ref: '#/components/schemas/GenericErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericErrorResponse'
  /diagnostic-report:
    post:
      tags:
        - HI Types
      summary: Create a Diagnostic Report
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DiagnosticReport'
      responses:
        '201':
          description: Successfully created
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/ValidationErrorResponse'
                  - $ref: '#/components/schemas/GenericErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericErrorResponse'
  /immunization:
    post:
      tags:
        - HI Types
      summary: Create an Immunization Record
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ImmunizationRecord'
      responses:
        '201':
          description: Successfully created
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/ValidationErrorResponse'
                  - $ref: '#/components/schemas/GenericErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericErrorResponse'
  /discharge-summary:
    post:
      tags:
        - HI Types
      summary: Create a Discharge Summary
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DischargeSummary'
      responses:
        '201':
          description: Successfully created
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/ValidationErrorResponse'
                  - $ref: '#/components/schemas/GenericErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericErrorResponse'
  /wellness-record:
    post:
      tags:
        - HI Types
      summary: Create a Wellness Record
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WellnessRecord'
      responses:
        '201':
          description: Successfully created
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/ValidationErrorResponse'
                  - $ref: '#/components/schemas/GenericErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericErrorResponse'
  /invoice:
    post:
      tags:
        - Billing
      summary: Create an Invoice Bundle
      description: Submits an invoice bundle containing patient, practitioner, organization, charge items, and payment details.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InvoiceBundleRequest'
            example:
              bundleType: Invoice
              careContextReference: visit-2025-08-20T10:00:00Z
              invoiceDate: 2025-08-12T10:30:00+05:30
              status: issued
              encounter: ""
              patient:
                name: Venu Ajitesh
                patientReference: ajitesh6x
                gender: male
                birthDate: 1940-04-27
              practitioners:
                - name: Dr.Venu Ajitesh
                  practitionerId: Predator
              organisation:
                facilityName: Predator_HIP
                facilityId: Predator_HIP
              invoice:
                id: INV-12345
                status: issued
                type: Pharmacy
                date: 2025-08-12T10:30:00+05:30
                totalNet: 2000.00
                totalGross: 2200.00
                currency: INR
                paymentTerms: Due in 15 days
                note: Surgery + post-op medicines
              chargeItems:
                - id: CHG-002
                  productType: medication
                  chargeType: Pharmacy
                  status: billed
                  description: Amoxicillin 500mg
                  quantity: 14
                  price:
                    - priceType: base
                      amount: 100
                  medication:
                    medicineName: AMOX500
                    manufacturer: ABC Pharma
                    medicationForm: tablet
                    lotNumber: ABC123
                    expiryDate: 2026-05-01
                - id: CHG-003
                  productType: device
                  chargeType: OPD
                  status: billed
                  description: Surgical Gloves
                  quantity: 5
                  price:
                    - priceType: base
                      amount: 200
                  device:
                    udiCarrier: UDI-GLV-001
                    manufacturer: MedGlove Inc.
                    modelNumber: MG-GLV-SRG
                    lotNumber: 194847-0
                    serialNumber: SN-98347
                    manufactureDate: 2025-01-10
                    expirationDate: 2028-01-10
                    status: active
                    safety:
                      - Latex Free
                      - Sterile
                    deviceName: Surgical Gloves
                    note: Used for major surgery
                - id: CHG-004
                  productType: substance
                  chargeType: IPD
                  status: billed
                  description: Lab Reagent Kit
                  quantity: 1
                  price:
                    - priceType: base
                      amount: 300
                  substance:
                    id: SUB-001
                    code: LAB-REAGENT-001
                    category: chemical
                    description: Used to treat infections
                    expiry: 2026-05-01
                    quantity: 2.0
              payment:
                method: upi
                status: active
                paymentDate: 2025-08-12T11:00:00+05:30
                paidAmount: 2200.00
                transactionId: TXN-98765
      responses:
        '201':
          description: Successfully created
          content:
            application/json:
              example:
                resourceType: Bundle
                id: 81ab25d0-82a0-41b5-b3a6-bff89356bce0
                meta:
                  versionId: '1'
                  lastUpdated: '2025-08-19T22:19:11.777Z'
                  profile:
                    - 'https://nrces.in/ndhm/fhir/r4/StructureDefinition/DocumentBundle'
                  security:
                    - system: 'http://terminology.hl7.org/CodeSystem/v3-Confidentiality'
                      code: V
                      display: very restricted
                identifier:
                  system: 'https://ABDM_WRAPPER/bundle'
                  value: 'visit-2025-08-19T22:19:11.395Z'
                type: document
                timestamp: '2025-08-19T22:19:11.774Z'
                entry:
                  - fullUrl: Composition/0f545f1a-64b5-437a-824e-ebb22b1bf720
                    resource:
                      resourceType: Composition
                      id: 0f545f1a-64b5-437a-824e-ebb22b1bf720
                      meta:
                        versionId: '1'
                        lastUpdated: '2025-08-19T22:19:11.921Z'
                      identifier:
                        system: 'https://ABDM_WRAPPER/bundle'
                        value: 0f545f1a-64b5-437a-824e-ebb22b1bf720
                      status: final
                      type:
                        coding:
                          - system: 'http://snomed.info/sct'
                            code: Invoice Record
                            display: Invoice Record
                      subject:
                        reference: Patient/94ecc23e-c798-4023-bcb2-15cd687166c4
                        type: Patient
                        display: Venu Ajitesh
                      date: '2024-05-01T12:03:37+05:30'
                      author:
                        - reference: Practitioner/Predator
                          type: Practitioner
                          display: Dr.Venu Ajitesh
                      title: Invoice Record
                      custodian:
                        reference: Organisation/ec12d2da-22f2-4b05-9cd6-5c66efa0853f
                        type: Organisation
                      section:
                        - title: Invoice
                          code:
                            coding:
                              - system: 'http://snomed.info/sct'
                                code: Invoice Record
                                display: Invoice Record
                            text: Invoice Record
                          entry:
                            - reference: Invoice/INV-12345
                              type: Invoice
                            - reference: ChargeItem/CHG-002
                              type: ChargeItem
                            - reference: ChargeItem/CHG-003
                              type: ChargeItem
                            - reference: ChargeItem/CHG-004
                              type: ChargeItem
                            - reference: Device/UDI-GLV-001
                              type: Device
                            - reference: Substance/a54eb8ca-a9bd-4147-90d5-51eb953b2965
                              type: Substance
                            - reference: Medication/1882f644-ee31-497d-b9ab-3c8350584659
                              type: Medication
                            - reference: PaymentReconciliation/b2fb26bb-b286-4487-bc9c-512f564220f0
                              type: PaymentReconciliation
                  - fullUrl: Patient/94ecc23e-c798-4023-bcb2-15cd687166c4
                    resource:
                      resourceType: Patient
                      id: 94ecc23e-c798-4023-bcb2-15cd687166c4
                      meta:
                        versionId: '1'
                        lastUpdated: '2025-08-19T22:19:11.778Z'
                        profile:
                          - 'https://nrces.in/ndhm/fhir/r4/StructureDefinition/Patient'
                      identifier:
                        - type:
                            coding:
                              - system: 'http://terminology.hl7.org/CodeSystem/v2-0203'
                                code: MR
                                display: Medical record number
                          system: 'https://healthid.abdm.gov.in'
                          value: ajitesh6x
                      name:
                        - text: Venu Ajitesh
                      gender: male
                      birthDate: '1940-04-27'
                  - fullUrl: Practitioner/Predator
                    resource:
                      resourceType: Practitioner
                      id: Predator
                      meta:
                        versionId: '1'
                        lastUpdated: '2025-08-19T22:19:11.795Z'
                        profile:
                          - 'https://nrces.in/ndhm/fhir/r4/StructureDefinition/Practitioner'
                      identifier:
                        - type:
                            coding:
                              - system: 'http://terminology.hl7.org/CodeSystem/v2-0203'
                                code: MR
                                display: Medical record number
                          system: 'https://doctor.abdm.gov.in'
                          value: Predator
                      name:
                        - text: Dr.Venu Ajitesh
                  - fullUrl: Organisation/ec12d2da-22f2-4b05-9cd6-5c66efa0853f
                    resource:
                      resourceType: Organization
                      id: ec12d2da-22f2-4b05-9cd6-5c66efa0853f
                      meta:
                        versionId: '1'
                        lastUpdated: '2025-08-19T22:19:11.797Z'
                        profile:
                          - 'https://nrces.in/ndhm/fhir/r4/StructureDefinition/Organization'
                      identifier:
                        - type:
                            coding:
                              - system: 'http://terminology.hl7.org/CodeSystem/v2-0203'
                                code: PRN
                                display: Provider number
                          system: 'https://facility.abdm.gov.in'
                          value: Predator_HIP
                      name: Predator_HIP
                  - fullUrl: Encounter/871368c4-1701-4ea6-bef1-aa590218eba5
                    resource:
                      resourceType: Encounter
                      id: 871368c4-1701-4ea6-bef1-aa590218eba5
                      meta:
                        lastUpdated: '2025-08-19T22:19:11.808Z'
                        profile:
                          - 'https://nrces.in/ndhm/fhir/r4/StructureDefinition/Encounter'
                      status: in-progress
                      class:
                        system: 'http://terminology.hl7.org/CodeSystem/v3-Confidentiality'
                        code: AMB
                        display: Ambulatory
                      subject:
                        reference: Patient/94ecc23e-c798-4023-bcb2-15cd687166c4
                        display: Venu Ajitesh
                      period:
                        start: '2024-05-01T06:33:37Z'
                  - fullUrl: Manufacturer/e9f1c715-19a3-463b-ae5b-cafe2d1466ab
                    resource:
                      resourceType: Organization
                      id: e9f1c715-19a3-463b-ae5b-cafe2d1466ab
                      meta:
                        versionId: '1'
                        lastUpdated: '2025-08-19T22:19:11.873Z'
                        profile:
                          - 'https://nrces.in/ndhm/fhir/r4/StructureDefinition/Organization'
                      identifier:
                        - type:
                            coding:
                              - system: 'http://terminology.hl7.org/CodeSystem/v2-0203'
                                code: PRN
                                display: Provider number
                          system: 'https://facility.abdm.gov.in'
                          value: 3ac2e25a-490c-424d-a19c-e541114f8f7e
                      name: ABC Pharma
                  - fullUrl: Invoice/INV-12345
                    resource:
                      resourceType: Invoice
                      id: INV-12345
                      status: issued
                      type:
                        text: Pharmacy
                      subject:
                        reference: Patient/94ecc23e-c798-4023-bcb2-15cd687166c4
                        display: Venu Ajitesh
                      date: '2024-05-01T12:03:37+05:30'
                      issuer:
                        reference: Organisation/ec12d2da-22f2-4b05-9cd6-5c66efa0853f
                        display: Predator_HIP
                      lineItem:
                        - chargeItemReference:
                            reference: ChargeItem/CHG-002
                          priceComponent:
                            - type: base
                              code:
                                coding:
                                  - system: 'http://hl7.org/fhir/invoice-priceComponentType'
                                    code: base
                                    display: base
                                text: base
                              amount:
                                value: 100
                                currency: INR
                        - chargeItemReference:
                            reference: ChargeItem/CHG-003
                          priceComponent:
                            - type: base
                              code:
                                coding:
                                  - system: 'http://hl7.org/fhir/invoice-priceComponentType'
                                    code: base
                                    display: base
                                text: base
                              amount:
                                value: 200
                                currency: INR
                        - chargeItemReference:
                            reference: ChargeItem/CHG-004
                          priceComponent:
                            - type: base
                              code:
                                coding:
                                  - system: 'http://hl7.org/fhir/invoice-priceComponentType'
                                    code: base
                                    display: base
                                text: base
                              amount:
                                value: 300
                                currency: INR
                      totalNet:
                        value: 2000
                        currency: INR
                      totalGross:
                        value: 2200
                        currency: INR
                      paymentTerms: Due in 15 days
                      note:
                        - text: Surgery + post-op medicines
                  - fullUrl: ChargeItem/CHG-002
                    resource:
                      resourceType: ChargeItem
                      id: CHG-002
                      identifier:
                        - value: medication
                      status: billed
                      code:
                        coding:
                          - system: 'https://nrces.in/ndhm/fhir/r4/CodeSystem/ndhm-billing-codes'
                            code: '01'
                            display: Pharmacy
                        text: Pharmacy
                      quantity:
                        value: 14
                        unit: pcs
                      productReference:
                        reference: Medication/1882f644-ee31-497d-b9ab-3c8350584659
                      note:
                        - text: Amoxicillin 500mg
                  - fullUrl: ChargeItem/CHG-003
                    resource:
                      resourceType: ChargeItem
                      id: CHG-003
                      identifier:
                        - value: device
                      status: billed
                      code:
                        coding:
                          - system: 'https://nrces.in/ndhm/fhir/r4/CodeSystem/ndhm-billing-codes'
                            code: '03'
                            display: OPD
                        text: OPD
                      quantity:
                        value: 5
                        unit: pcs
                      productReference:
                        reference: Device/UDI-GLV-001
                      note:
                        - text: Surgical Gloves
                  - fullUrl: ChargeItem/CHG-004
                    resource:
                      resourceType: ChargeItem
                      id: CHG-004
                      identifier:
                        - value: substance
                      status: billed
                      code:
                        coding:
                          - system: 'https://nrces.in/ndhm/fhir/r4/CodeSystem/ndhm-billing-codes'
                            code: '02'
                            display: IPD
                        text: IPD
                      quantity:
                        value: 1
                        unit: pcs
                      productReference:
                        reference: Substance/a54eb8ca-a9bd-4147-90d5-51eb953b2965
                      note:
                        - text: Lab Reagent Kit
                  - fullUrl: Device/UDI-GLV-001
                    resource:
                      resourceType: Device
                      id: UDI-GLV-001
                      udiCarrier:
                        - deviceIdentifier: UDI-GLV-001
                      status: active
                      manufacturer: MedGlove Inc.
                      manufactureDate: '2025-01-10T00:00:00+05:30'
                      expirationDate: '2028-01-10T00:00:00+05:30'
                      lotNumber: 194847-0
                      serialNumber: SN-98347
                      deviceName:
                        - name: Surgical Gloves
                          type: user-friendly-name
                      modelNumber: MG-GLV-SRG
                      note:
                        - text: Used for major surgery
                      safety:
                        - text: Latex Free
                        - text: Sterile
                  - fullUrl: Substance/a54eb8ca-a9bd-4147-90d5-51eb953b2965
                    resource:
                      resourceType: Substance
                      id: a54eb8ca-a9bd-4147-90d5-51eb953b2965
                      category:
                        - text: chemical
                      code:
                        text: LAB-REAGENT-001
                      description: Used to treat infections
                      instance:
                        - expiry: '2025-08-20T03:49:11+05:30'
                          quantity:
                            value: 2
                  - fullUrl: Medication/1882f644-ee31-497d-b9ab-3c8350584659
                    resource:
                      resourceType: Medication
                      id: 1882f644-ee31-497d-b9ab-3c8350584659
                      meta:
                        versionId: '1'
                        lastUpdated: '2025-08-19T22:19:11.878Z'
                      code:
                        coding:
                          - system: 'http://snomed.info/sct'
                            code: '261665006'
                            display: AMOX500
                        text: AMOX500
                      manufacturer:
                        reference: Manufacturer/e9f1c715-19a3-463b-ae5b-cafe2d1466ab
                      form:
                        coding:
                          - system: 'http://snomed.info/sct'
                            code: '385055001'
                            display: tablet
                        text: tablet
                      batch:
                        lotNumber: ABC123
                        expirationDate: '2025-08-20T03:49:11+05:30'
                  - fullUrl: PaymentReconciliation/b2fb26bb-b286-4487-bc9c-512f564220f0
                    resource:
                      resourceType: PaymentReconciliation
                      id: b2fb26bb-b286-4487-bc9c-512f564220f0
                      status: active
                      paymentAmount:
                        value: 2200
                        currency: INR
                      paymentIdentifier:
                        value: TXN-98765
                      detail:
                        - type:
                            coding:
                              - system: 'http://terminology.hl7.org/CodeSystem/payment-type'
                                code: upi
                                display: upi



        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/ValidationErrorResponse'
                  - $ref: '#/components/schemas/GenericErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericErrorResponse'

components:
  schemas:
    OPConsultRecord:
      type: object
      properties:
        bundleType:
          type: string
          enum:
            - OPConsultRecord
        careContextReference:
          type: string
          example: visit 21-03-2025
        visitDate:
          type: string
          format: date
          example: 2000-06-23
        patient:
          $ref: '#/components/schemas/Patient'
        practitioners:
          type: array
          items:
            $ref: '#/components/schemas/Practitioner'
        organisation:
          $ref: '#/components/schemas/Organisation'
        chiefComplaints:
          type: array
          items:
            $ref: '#/components/schemas/ChiefComplaint'
        physicalExaminations:
          type: array
          items:
            $ref: '#/components/schemas/PhysicalExamination'
        allergies:
          type: array
          items:
            type: string
        medicalHistories:
          type: array
          items:
            $ref: '#/components/schemas/ChiefComplaint'
        familyHistories:
          type: array
          items:
            $ref: '#/components/schemas/FamilyHistory'
        serviceRequests:
          type: array
          items:
            $ref: '#/components/schemas/ServiceRequest'
        medications:
          type: array
          items:
            $ref: '#/components/schemas/Medication'
        followups:
          type: array
          items:
            $ref: '#/components/schemas/FollowUp'
        procedures:
          type: array
          items:
            $ref: '#/components/schemas/Procedure'
        referrals:
          type: array
          items:
            $ref: '#/components/schemas/Referral'
        otherObservations:
          type: array
          items:
            $ref: '#/components/schemas/OtherObservation'
        documents:
          type: array
          items:
            $ref: '#/components/schemas/Document'
      required:
        - bundleType
        - patient
        - practitioners
        - careContextReference
        - authoredOn
    PrescriptionRecord:
      type: object
      properties:
        bundleType:
          type: string
          enum:
            - PrescriptionRecord
        careContextReference:
          type: string
          example: visit-{{$isoTimestamp}}
        authoredOn:
          type: string
          format: date
          example: 2001-05-22
        encounter:
          type: string
          example: ""
        patient:
          $ref: '#/components/schemas/Patient'
        practitioners:
          type: array
          items:
            $ref: '#/components/schemas/Practitioner'
        organisation:
          $ref: '#/components/schemas/Organisation'
        prescriptions:
          type: array
          items:
            $ref: '#/components/schemas/Medication'
        documents:
          type: array
          items:
            $ref: '#/components/schemas/Document'
      required:
        - bundleType
        - patient
        - practitioners
        - careContextReference
        - authoredOn
        - prescriptions
      example:
        bundleType: PrescriptionRecord
        careContextReference: visit-{{$isoTimestamp}}
        authoredOn: 2001-05-22
        encounter: ""
        patient:
          name: Venu Ajitesh
          patientReference: ajitesh6x
          gender: male
          birthDate: 2001-04-27
        practitioners:
          - name: Dr.Venu Ajitesh
            practitionerId: Predator
        organisation:
          facilityName: Predator_HIP
          facilityId: Predator_HIP
        prescriptions:
          - medicine: Dolo
            dosage: 1-0-1
            timing: 1-1-D
            route: Oral
            method: swallow
            additionalInstructions: Take them after food
            reason: Fever
        documents:
          - type: Prescription
            contentType: application/pdf
            data: JVBERi0xLjMKJf////8K
    HealthDocumentRecord:
      type: object
      properties:
        bundleType:
          type: string
          enum:
            - HealthDocumentRecord
        careContextReference:
          type: string
          example: visist 21-03-2024
        patient:
          $ref: '#/components/schemas/Patient'
        authoredOn:
          type: string
          format: date
          example: 2001-04-27
        practitioners:
          type: array
          items:
            $ref: '#/components/schemas/Practitioner'
        organisation:
          $ref: '#/components/schemas/Organisation'
        encounter:
          type: string
          example: ""
        documents:
          type: array
          items:
            $ref: '#/components/schemas/Document'
      required:
        - bundleType
        - patient
        - practitioners
        - careContextReference
        - authoredOn
        - documents
      example:
        bundleType: HealthDocumentRecord
        careContextReference: visist 21-03-2024
        patient:
          name: Venu Ajitesh
          patientReference: ajitesh6x
          gender: male
          birthDate: 2001-04-27
        date: 2001-04-27
        practitioners:
          - name: Dr.Venu Ajitesh
            practitionerId: Predator
        organisation:
          facilityName: Predator_HIP
          facilityId: Predator_HIP
        encounter: ""
        documents:
          - contentType: application/pdf
            data: xyzadybcljbabvlalbfdbvubujzbj
    DiagnosticReport:
      type: object
      properties:
        bundleType:
          type: string
          enum:
            - DiagnosticReport
        careContextReference:
          type: string
          example: visist 21-03-2024
        authoredOn:
          type: string
          format: date
          example: 2024-05-20
        patient:
          $ref: '#/components/schemas/Patient'
        practitioners:
          type: array
          items:
            $ref: '#/components/schemas/Practitioner'
        organisation:
          $ref: '#/components/schemas/Organisation'
        encounter:
          type: string
          example: Ambula
        diagnostics:
          type: array
          items:
            $ref: '#/components/schemas/Diagnostic'
        documents:
          type: array
          items:
            $ref: '#/components/schemas/Document'
      required:
        - bundleType
        - patient
        - practitioners
        - careContextReference
        - authoredOn
        - diagnostics
      example:
        bundleType: DiagnosticReport
        careContextReference: visist 21-03-2024
        authoredOn: 2024-05-20
        patient:
          name: Venu Ajitesh
          patientReference: ajitesh6x
          gender: male
          birthDate: 2001-04-27
        practitioners:
          - name: Dr.Venu Ajitesh
            practitionerId: Predator
        organisation:
          facilityName: Predator_HIP
          facilityId: Predator_HIP
        encounter: Ambula
        diagnostics:
          - serviceName: BloodTest
            serviceCategory: Hematography
            result:
              - observation: Height
                result: Normal
                valueQuantity:
                  unit: CM
                  value: 170
            conclusion: Normal
            presentedForm:
              contentType: application/pdf
              data: skciybewydcugueducuyeduychidhyuchyedyhcb
        documents:
          - contentType: pdf
            data: xyzadybcljbabvlalbfdbvubujzbj

    ImmunizationRecord:
      type: object
      properties:
        bundleType:
          type: string
          enum:
            - ImmunizationRecord
        careContextReference:
          type: string
          example: visit-{{$isoTimestamp}}
        patient:
          $ref: '#/components/schemas/Patient'
        practitioners:
          type: array
          items:
            $ref: '#/components/schemas/Practitioner'
        organisation:
          $ref: '#/components/schemas/Organisation'
        immunizations:
          type: array
          items:
            $ref: '#/components/schemas/Immunization'
        documents:
          type: array
          items:
            $ref: '#/components/schemas/Document'
      required:
        - bundleType
        - patient
        - practitioners
        - careContextReference
        - authoredOn
        - immunizations
      example:
        bundleType: ImmunizationRecord
        careContextReference: visit-{{$isoTimestamp}}
        patient:
          name: Venu Ajitesh
          patientReference: ajitesh6x
          gender: male
          birthDate: 2001-04-27
        practitioners:
          - name: Dr.Venu Ajitesh
            practitionerId: Predator
        organisation:
          facilityName: Predator_HIP
          facilityId: Predator_HIP
        immunizations:
          - date: 2024-06-15
            vaccineName: Covaxin
            lotNumber: IN00004
            manufacturer: NHA
            doseNumber: 3
        documents:
          - type: immunization
            contentType: application/pdf
            data: xyzadybcljbabvlalbfdbvubujzbj
    DischargeSummary:
      type: object
      properties:
        bundleType:
          type: string
          enum:
            - discharge-summary
        careContextReference:
          type: string
          example: visist 21-03-2024
        patient:
          $ref: '#/components/schemas/Patient'
        practitioners:
          type: array
          items:
            $ref: '#/components/schemas/Practitioner'
        organisation:
          $ref: '#/components/schemas/Organisation'
        chiefComplaints:
          type: array
          items:
            $ref: '#/components/schemas/ChiefComplaint'
        physicalExaminations:
          type: array
          items:
            $ref: '#/components/schemas/PhysicalExamination'
        allergies:
          type: array
          items:
            type: string
        medicalHistories:
          type: array
          items:
            $ref: '#/components/schemas/ChiefComplaint'
        familyHistories:
          type: array
          items:
            $ref: '#/components/schemas/FamilyHistory'
        authoredOn:
          type: string
          format: date
        medications:
          type: array
          items:
            $ref: '#/components/schemas/Medication'
        diagnostics:
          type: array
          items:
            $ref: '#/components/schemas/Diagnostic'
        procedures:
          type: array
          items:
            $ref: '#/components/schemas/Procedure'
        documents:
          type: array
          items:
            $ref: '#/components/schemas/Document'
      required:
        - bundleType
        - patient
        - practitioners
        - careContextReference
        - authoredOn
      example:
        bundleType: discharge-summary
        careContextReference: visist 21-03-2024
        patient:
          name: Venu Ajitesh
          patientReference: ajitesh6x
          gender: male
          birthDate: 2001-04-27
        practitioners:
          - name: Dr.Venu Ajitesh
            practitionerId: Predator
        organisation:
          facilityName: Predator_HIP
          facilityId: Predator_HIP
        chiefComplaints:
          - complaint: Sugar
            recordedDate: 2024-05-20
            dateRange:
              from: 2018-04-27
              to: 2018-05-26
        medications:
          - medicine: Dolo
            dosage: 1-0-1
            timing: 1-1-D
            route: Oral
            method: swallow
            additionalInstructions: Take them after food
        physicalExaminations:
          - observation: Height
            valueQuantity:
              unit: CM
              value: 170
        allergies:
          - Walnuts
        medicalHistories:
          - complaint: Sugar
            recordedDate: 2024-05-20
            dateRange:
              from: 2018-04-27
              to: 2018-05-26
        familyHistories:
          - relationship: Friend
            observation: Toxic
        diagnostics:
          - serviceName: BloodTest
            serviceCategory: Hematography
            result:
              - observation: Height
                result: Normal
                valueQuantity:
                  unit: CM
                  value: 170
            conclusion: Normal
            presentedForm:
              contentType: application/pdf
              data: skciybewydcugueducuyeduychidhyuchyedyhcb
        procedures:
          - status: INPROGRESS
            condition: Severe
            outcome: Healthy
            details: Operation
        documents:
          - type: OP record
            contentType: application/pdf
            data: xyzadybcljbabvlalbfdbvubujzbj
    WellnessRecord:
      type: object
      properties:
        bundleType:
          type: string
          enum:
            - wellness-record
        careContextReference:
          type: string
          example: visist 21-03-2025
        patient:
          $ref: '#/components/schemas/Patient'
        practitioners:
          type: array
          items:
            $ref: '#/components/schemas/Practitioner'
        organisation:
          $ref: '#/components/schemas/Organisation'
        vitalSigns:
          type: array
          items:
            $ref: '#/components/schemas/Observation'
        bodyMeasurements:
          type: array
          items:
            $ref: '#/components/schemas/Observation'
        physicalActivities:
          type: array
          items:
            $ref: '#/components/schemas/Observation'
        generalAssessments:
          type: array
          items:
            $ref: '#/components/schemas/Observation'
        womanHealths:
          type: array
          items:
            $ref: '#/components/schemas/Observation'
        lifeStyles:
          type: array
          items:
            $ref: '#/components/schemas/Observation'
        otherObservations:
          type: array
          items:
            $ref: '#/components/schemas/Observation'
        documents:
          type: array
          items:
            $ref: '#/components/schemas/Document'
      required:
        - bundleType
        - patient
        - practitioners
        - careContextReference
      example:
        bundleType: wellness-record
        careContextReference: visist 21-03-2025
        patient:
          name: Venu Ajitesh
          patientReference: ajitesh6x
          gender: male
          birthDate: 2001-04-27
        practitioner:
          - name: Dr.Venu Ajitesh
            practitionerId: Predator
        organisation:
          facilityName: Predator_HIP
          facilityId: Predator_HIP
        vitalSigns:
          - observation: Height
            result: Normal
            valueQuantity:
              unit: CM
              value: 170
        bodyMeasurements:
          - observation: Height
            result: Normal
            valueQuantity:
              unit: CM
              value: 170
        physicalActivities:
          - observation: Height
            result: Normal
            valueQuantity:
              unit: CM
              value: 170
        generalAssessments:
          - observation: Height
            result: Normal
            valueQuantity:
              unit: CM
              value: 170
        womanHealths:
          - observation: Height
            result: Normal
            valueQuantity:
              unit: CM
              value: 170
        lifeStyles:
          - observation: Height
            result: Normal
            valueQuantity:
              unit: CM
              value: 170
        otherObservations:
          - observation: Height
            result: Normal
            valueQuantity:
              unit: CM
              value: 170
        documents:
          - type: Prescription
            contentType: application/pdf
            data: JVBERi0xLjMKJf////8KOCAwIG9iago8PAovVHlwZSAvRXh0R1N0YXRlCi9jYSAxCj4

    Patient:
      type: object
      properties:
        name:
          type: string
        patientReference:
          type: string
        gender:
          type: string
          enum:
            - male
            - female
        birthDate:
          type: string
          format: date
      required:
        - name
        - patientReference
      example:
        name: Venu Ajitesh
        patientReference: ajitesh6x
        gender: male
        birthDate: 2001-04-27

    Practitioner:
      type: object
      properties:
        name:
          type: string
        practitionerId:
          type: string
      required:
        - name
      example:
        name: Dr.Venu Ajitesh
        practitionerId: Predator

    Organisation:
      type: object
      properties:
        facilityName:
          type: string
        facilityId:
          type: string
      required:
        - facilityName
      example:
        facilityName: Predator_HIP
        facilityId: Predator_HIP
    Diagnostic:
      type: object
      properties:
        serviceName:
          type: string
        serviceCategory:
          type: string
        result:
          type: array
          items:
            $ref: '#/components/schemas/Observation'
        conclusion:
          type: string
        presentedForm:
          $ref: '#/components/schemas/Document'
      required:
        - serviceName
        - serviceCategory
        - result
      example:
        serviceName: BloodTest
        serviceCategory: Hematography
        result:
          - observation: Height
            result: Normal
            valueQuantity:
              unit: CM
              value: 170
        conclusion: Normal
        presentedForm:
          contentType: application/pdf
          data: skciybewydcugueducuyeduychidhyuchyedyhcb
    Immunization:
      type: object
      properties:
        date:
          type: string
          format: date
        vaccineName:
          type: string
        lotNumber:
          type: string
        manufacturer:
          type: string
        doseNumber:
          type: string
      required:
        - date
        - vaccineName
      example:
        date: 2024-06-15
        vaccineName: Covaxin
        lotNumber: IN00004
        manufacturer: NHA
        doseNumber: 3

    DiagnosticResult:
      type: object
      properties:
        observation:
          type: string
        result:
          type: string
        valueQuantity:
          $ref: '#/components/schemas/ValueQuantity'
      required:
        - observation
      example:
        observation: Height
        result: Normal
        valueQuantity:
          unit: CM
          value: 170

    ChiefComplaint:
      type: object
      properties:
        complaint:
          type: string
        recordedDate:
          type: string
          format: date
        dateRange:
          $ref: '#/components/schemas/DateRange'
      required:
        - complaint
        - recordedDate
      example:
        complaint: Sugar
        recordedDate: 2024-05-20
        dateRange:
          from: 2018-04-27
          to: 2018-05-26

    DateRange:
      type: object
      properties:
        from:
          type: string
          format: date
        to:
          type: string
          format: date
      example:
        from: 2018-04-27
        to: 2018-05-26

    PhysicalExamination:
      type: object
      properties:
        observation:
          type: string
        result:
          type: string
        valueQuantity:
          $ref: '#/components/schemas/ValueQuantity'
      required:
        - observation
      example:
        observation: Height
        result: Normal
        valueQuantity:
          unit: CM
          value: 170

    ValueQuantity:
      type: object
      properties:
        unit:
          type: string
        value:
          type: number
      required:
        - unit
        - value
      example:
        unit: KG
        value: 90

    FamilyHistory:
      type: object
      properties:
        relationship:
          type: string
        observation:
          type: string
      required:
        - relationship
        - observation
      example:
        relationship: Friend
        observation: Toxic

    ServiceRequest:
      type: object
      properties:
        status:
          type: string
        details:
          type: string
        specimen:
          type: string
      required:
        - status
        - details
      example:
        status: ACTIVE
        details: X-RAY
        specimen: Jhonsons

    Medication:
      type: object
      properties:
        medicine:
          type: string
        dosage:
          type: string
        timing:
          description: frequency-period-periodUnit
          type: string
          enum: [S,MIN,H,D,WK,MO]
        route:
          type: string
        method:
          type: string
        additionalInstructions:
          type: string
        reason:
          type: string
      required:
        - medicine
        - dosage
      example:
        medicine: Dolo
        dosage: 1-0-1
        timing: 1-1-D
        route: Oral
        method: swallow
        additionalInstructions: Take them after food
        reason: Fever


    FollowUp:
      type: object
      properties:
        serviceType:
          type: string
        appointmentTime:
          type: string
          format: date
        reason:
          type: string
      required:
        - serviceType
        - appointmentTime
        - reason
      example:
        serviceType: OPConsultation
        appointmentTime: 2024-05-20
        reason: General

    Procedure:
      type: object
      properties:
        date:
          type: string
        status:
          type: string
        procedureReason:
          type: string
        outcome:
          type: string
        procedureName:
          type: string
      required:
        - date
        - status
        - procedureName
        - procedureReason
      example:
        date: 2001-04-25
        status: INPROGRESS
        procedureReason: Severe
        outcome: Healthy
        procedureName: Operation

    Referral:
      type: object
      properties:
        status:
          type: string
        details:
          type: string
        specimen:
          type: string
      required:
        - status
        - details
      example:
        status: ACTIVE
        details: Y-RAY
        specimen: Rock

    Observation:
      type: object
      properties:
        observation:
          type: string
        result:
          type: string
        valueQuantity:
          $ref: '#/components/schemas/ValueQuantity'
      required:
        - observation
      example:
        observation: Height
        result: Normal
        valueQuantity:
          unit: CM
          value: 170

    OtherObservation:
      type: object
      properties:
        observation:
          type: string
        result:
          type: string
        valueQuantity:
          $ref: '#/components/schemas/ValueQuantity'
      required:
        - observation
      example:
        observation: weight
        result: Over weight
        valueQuantity:
          unit: KG
          value: 90
      # Note: Either result or valueQuantity should be included along with observation.

    Document:
      type: object
      properties:
        type:
          type: string
        contentType:
          type: string
        data:
          type: string
      required:
        - type
        - contentType
        - data
      example:
        type: OP record
        contentType: application/pdf
        data: xyzadybcljbabvlalbfdbvubujzbj
    InvoiceBundleRequest:
      type: object
      required:
        - bundleType
        - careContextReference
        - invoiceDate
        - status
        - patient
        - organisation
        - invoice
        - chargeItems
      properties:
        bundleType:
          type: string
          example: Invoice
        careContextReference:
          type: string
        invoiceDate:
          type: string
          format: date-time
        status:
          type: string
          enum: [issued, balanced, cancelled, draft, entered-in-error]
        encounter:
          type: string
        patient:
          $ref: '#/components/schemas/Patient'
        practitioners:
          type: array
          items:
            $ref: '#/components/schemas/Practitioner'
        organisation:
          $ref: '#/components/schemas/Organisation'
        invoice:
          $ref: '#/components/schemas/Invoice'
        chargeItems:
          type: array
          items:
            $ref: '#/components/schemas/ChargeItem'
        payment:
          $ref: '#/components/schemas/Payment'



    Invoice:
      type: object
      required:
        - status
        - type
        - totalNet
        - totalGross
        - currency
        - date
      properties:
        id:
          type: string
        status:
          type: string
          enum: [issued, balanced, cancelled, draft, entered-in-error]
        type:
          type: string
          enum: [Consultation, Pharmacy, IPD, OPD, Others]
        date:
          type: string
          format: date-time
        totalNet:
          type: number
          format: double
        totalGross:
          type: number
          format: double
        currency:
          type: string
        paymentTerms:
          type: string
        note:
          type: string

    ChargeItem:
      type: object
      required:
        - productType
        - chargeType
        - status
        - quantity
        - price
        - description
      properties:
        id:
          type: string
        productType:
          type: string
          enum: [medication, device, substance]
        chargeType:
          type: string
        status:
          type: string
          enum: [planned, billable, not-billable, aborted, billed, entered-in-error, unknown]
        description:
          type: string
        quantity:
          type: integer
        price:
          type: array
          items:
            $ref: '#/components/schemas/Price'
        medication:
          $ref: '#/components/schemas/InvoiceMedication'
        device:
          $ref: '#/components/schemas/Device'
        substance:
          $ref: '#/components/schemas/Substance'

    Price:
      type: object
      required:
        - proceType
        - amount
      properties:
        priceType:
          type: string
          enum: [base, surcharge, deduction, discount, SGST, CGST, informational]
        amount:
          type: number
          format: double

    InvoiceMedication:
      type: object
      required:
        - medicineName
      properties:
        medicineName:
          type: string
        manufacturer:
          type: string
        medicationForm:
          type: string
        lotNumber:
          type: string
        expiryDate:
          type: string
          format: date-time

    Device:
      type: object
      required:
        - status
        - deviceName
      properties:
        udiCarrier:
          type: string
        manufacturer:
          type: string
        modelNumber:
          type: string
        lotNumber:
          type: string
        serialNumber:
          type: string
        manufactureDate:
          type: string
          format: date
        expirationDate:
          type: string
          format: date
        status:
          type: string
          enum: [active, inactive, entered-in-error, unknown]
        safety:
          type: array
          items:
            type: string
        deviceName:
          type: string
        note:
          type: string

    Substance:
      type: object
      required:
        - code
        - category
        - description
        - quantity
      properties:
        id:
          type: string
        code:
          type: string
        category:
          type: string
        description:
          type: string
        expiry:
          type: string
          format: date-time
        quantity:
          type: number
          format: double

    Payment:
      type: object
      required:
        - method
        - status
        - paymentAmount
      properties:
        method:
          type: string
          example: upi
        status:
          type: string
          enum: [active, cancelled, draft, entered-in-error, null]
        paymentDate:
          type: string
          format: date-time
        paidAmount:
          type: number
          format: double
        transactionId:
          type: string



    ValidationErrorResponse:
      type: object
      properties:
        validationErrors:
          type: object
          properties:
            code:
              type: integer
              example: 1000
            error:
              type: array
              items:
                type: object
                properties:
                  field:
                    type: string
                  message:
                    type: string
      example:
        validationErrors:
          code: 1000
          error:
            - field: bundleType
              message: must match "PrescriptionRecord"

    GenericErrorResponse:
      type: object
      properties:
        error:
          type: object
          properties:
            code:
              type: integer
            message:
              type: string
      example:
        error:
          code: 1000
          message: "Parsing error must match the date format 2002-05-12"
